name: flutter_json_api
description: A simple json api implemenation in flutter

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.0
  http: '>=0.11.3+12'

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
